### ISSUE TITLE
Code signing entitlements not found

### ISSUE THREAD

**Issue by HaakonL** [universal-tools/UTNotificationsFeedback#84] opened 2018-07-11 12:21 UTC
Hi,

after moving to Unity 2018.2 we are no longer able to build in Unity Cloud Build. We can build locally with xcode, but only if we manually set the entitlements file in xcode. Since we can't do any manual changes in Unity Cloud Build, this is a bug that needs a patch asap. I have no clue how to point you in the right direction. I guess you can create a new project in Unity 2018.2 with UT Notifications included and Build target set to IOS, and when you build for xcode you should see in xcode that the Code Signing Entitlements doesn't point to the [productname].entitlements file your IOSBuildPostprocessor generates.

The error I see in the cloud build logs is:

Code Signing Error: The file "/BUILD_PATH/abra.kadabra.ios/temp.XXXXXX20180710-4041-1hckdh7/kadabra.entitlements Unity-iPhone/kadabra.entitlements" could not be opened. Verify the value of the CODE_SIGN_ENTITLEMENTS build setting for target "Unity-iPhone" and build configuration "Release" is correct and that the file exists on disk.

**Comment by yuriy-universal-ivanov** [comment] 2018-07-12 21:23
Hi @HaakonL ,

Thank you, I can confirm the issue with Unity 2018.2. The fix is, fortunately, simple: in `Assets/UTNotifications/Src/iOS/Editor/IOSBuildPostprocessor.cs` comment out line 39:
```
//UpdatePushNotificationsCapability(pathToBuiltProject);
```

The root cause is very simple: Unity started doing the same thing as we've been doing since long time ago in that post build script to enable push notifications capabilities in iOS, so we got conflicts with them. This fix disables our patching.

We'll add a check to not patch anything in Unity 2018.2 and above in the next update.

By the way, you can take a look at a related post in Unity Answers: https://answers.unity.com/questions/1528377/how-to-disable-push-notifications-capability-in-io.html.

Please let me know if you're still facing any issues.

Best regards,
Yuriy, Universal Tools team.

**Comment by yuriy-universal-ivanov** [comment] 2018-08-07 21:59
Fixed in UTNotifications 1.7.4

**Closed as completed by yuriy-universal-ivanov** 2018-08-07 21:59 UTC
