### ISSUE TITLE
not receiving any test push notifications in SampleUI

### ISSUE THREAD

**Issue by QuangSang** [universal-tools/UTNotificationsFeedback#13] opened 2015-10-17 09:38 UTC
Hi,
I'm trying to set up Android push notification using UTnotification plugins, I followed the manual on how to configure GCM except for the demo server part. So I built and ran the scene and was able to retrieve the registrationId ( something like this APA91bG7CxW1axUiqCJ...) and providerName, so does that mean my device is already registered to GCM at this point? Assuming it is, I used that registrationId and the api key i got from the google developer console to try to send a test push using gcm_simple_sender (https://github.com/SeanZoR/gcm_simple_sender)
 But it gave me this error: 

{"multicast_id":6109172753378285212,"success":0,"failure":1,"canonical_ids":0,"results":[{"error":"NotRegistered"}]}

So any suggestion or feedback that could help me with this issue?

Thanks

**Comment by yuriy-universal-ivanov** [comment] 2015-10-17 11:51
Hi @QuangSang,

Successful getting the registration id indeed means that you configured everything right. So it should be some mistake in configuring the server or the way you send GCM message from it. Please, use the UTNotifications DemoServer to test if everything works. You can send us by email the complete server code you use to send GCM notifications, we'll find an issue.

As it's not a bug or feature request, I'm closing the issue.
Feel free to contact us with any questions by email: universal.tools.contact@gmail.com, we are always happy to help you!

Best regards,
Yuriy, Universal Tools team.

**Closed as completed by yuriy-universal-ivanov** 2015-10-17 11:51 UTC
