### ISSUE TITLE
Badge error

### ISSUE THREAD

**Issue by ghost** [universal-tools/UTNotificationsFeedback#61] opened 2017-07-04 10:07 UTC
Hi,

This error is happening on at least some Android 6 devices. For example an Acer B1-780. 

 Unable to execute badge:Unable to execute badge:unable to resolve intent: Intent { act=android.intent.action.BADGE_COUNT_UPDATE (has extras) } 

I'm setting the badge with notificationsManager.ScheduleNotification
And it will only set to -1 or 1.

I'm using 1.6.3 version of the plugin.

Regards,
Mathijs.

**Comment by yuriy-universal-ivanov** [comment] 2017-07-04 19:58
Hi @matie ,

It should be logged but not causing any issues (of course, including, app crashes). It just tells you that badges are not supported on that device, as detected by [ShortcutBadger ](https://github.com/leolin310148/ShortcutBadger) (as you can see, there are is Acer in the list of ShortcutBadger supported launchers). As you probably know, there are no badges in Android, but some custom launchers do add badges as extension. Badges will work only with these launchers on Android.

Please let me know if the error message causes any issues except non-working badges for you. Otherwise, it's not a bug.

Best regards,
Yuriy, Universal Tools team.

**Comment by yuriy-universal-ivanov** [comment] 2017-07-15 14:04
Hi @matie ,
Can I close the issue?

**Comment by michelesartoreilevia** [comment] 2017-09-15 07:42
Hi, @yuriy-universal-ivanov ,
I've this issues with badge in android 8 :

09-15 07:25:29.082  4120  4120 W Unity   : Failed to get permission info for com.sec.android.provider.badge.permission.READ, manifest likely missing custom permission declaration
09-15 07:25:29.082  4120  4120 W Unity   : Permission com.sec.android.provider.badge.permission.READ ignored
09-15 07:25:29.082  4120  4120 W Unity   : Failed to get permission info for com.sec.android.provider.badge.permission.WRITE, manifest likely missing custom permission declaration
09-15 07:25:29.082  4120  4120 W Unity   : Permission com.sec.android.provider.badge.permission.WRITE ignored
09-15 07:25:29.082  4120  4120 W Unity   : Failed to get permission info for com.htc.launcher.permission.READ_SETTINGS, manifest likely missing custom permission declaration
09-15 07:25:29.082  4120  4120 W Unity   : Permission com.htc.launcher.permission.READ_SETTINGS ignored
09-15 07:25:29.083  4120  4120 W Unity   : Failed to get permission info for com.htc.launcher.permission.UPDATE_SHORTCUT, manifest likely missing custom permission declaration
09-15 07:25:29.083  4120  4120 W Unity   : Permission com.htc.launcher.permission.UPDATE_SHORTCUT ignored
09-15 07:25:29.084  4120  4120 W Unity   : Failed to get permission info for com.sonyericsson.home.permission.BROADCAST_BADGE, manifest likely missing custom permission declaration
09-15 07:25:29.084  4120  4120 W Unity   : Permission com.sonyericsson.home.permission.BROADCAST_BADGE ignored
09-15 07:25:29.084  4120  4120 W Unity   : Failed to get permission info for com.anddoes.launcher.permission.UPDATE_COUNT, manifest likely missing custom permission declaration
09-15 07:25:29.084  4120  4120 W Unity   : Permission com.anddoes.launcher.permission.UPDATE_COUNT ignored
09-15 07:25:29.084  4120  4120 W Unity   : Failed to get permission info for com.majeur.launcher.permission.UPDATE_BADGE, manifest likely missing custom permission declaration
09-15 07:25:29.084  4120  4120 W Unity   : Permission com.majeur.launcher.permission.UPDATE_BADGE ignored
09-15 07:25:29.089  4120  4120 E Unity   : Unable to query for permission: Fragment null must be a public static class to be  properly recreated from instance state.

Is this an UTNotification issues ?

Thank's for the support.

Best regard,
Michele Sartore,

**Comment by michelesartoreilevia** [comment] 2017-09-15 08:04
I found this link on StackOverflow that I think is dealing about this issue. I hope it's helpfull:
https://stackoverflow.com/questions/39241305/fatal-exception-java-lang-securityexception-missing-permission-to-insert-badge

Thank's again

Best regard,
Michele Sartore

**Comment by yuriy-universal-ivanov** [comment] 2017-09-16 17:44
Hi @michelesartoregithub ,

I've replied you be email, but duplicating it here just in case.

These errors are not really errors - everything works as designed to. You probably know that until Android 8, there were no badges in Android. But some of the vendors and some custom launchers implemented their own custom badges. UTNotifications use ShortcutBadger Android library for showing badges on Android versions prior 8. It tries setting badges for each of the supported launchers. If it fails, an exception is thrown. It handles the exception and tries the next supported method. Each of this exceptions is logged, but it's completely fine, just ignore those messages.

Do you experience any problems with any of UTNotifications functionality? If yes, it has nothing to do with those messages. Please then describe any issues you're facing and I'll be happy to help you resolve them.

Best regards,
Yuriy, Universal Tools team.

**Comment by michelesartoreilevia** [comment] 2017-09-19 09:24
It is a Unity3D bug because if I build with version 2017.2.0b8 the app won't start, if I build with beta version 2017.2.0b11 the app work fine.
Thank's again @yuriy-universal-ivanov 
Best regard

**Closed as completed** 2017-10-03 18:35 UTC
